### ISSUE TITLE
fix QML_BAD_GUI_RENDER_LOOP

### ISSUE THREAD

**Issue by qCring** [qCring/QuickVtk#2]
Atm "QML_BAD_GUI_RENDER_LOOP" forces the application to run the UI on the main thread because forwarding QML events to VTK crashes the application.

**Comment by haampie** [comment]
any idea whether this can be fixed?

**Comment by qCring** [comment]
Hi Harmen :)
I'll try to narrow down what causes the crashes exactly. My guess is that this is related to the VTK interactor. QML events (from a separate thread B) are forwarded to VTK (on thread A) and the application crashes after a new render is requested from the "wrong" thread. An idea would be to use Qt's signals/slots in order to invoke the actual rendering method from the "right" thread.

So instead of calling `m_interactor->InvokeEvent` directly from `FboRenderer::onMouseEvent`, it might fix the problem to implement this via signals/slots since they provide the ability to execute slots on a different thread via [QueuedConnection](https://doc.qt.io/archives/qt-4.8/qt.html#ConnectionType-enum)

**Comment by qCring** [comment]
Okay, I just run the application on macOS and Windows with `_putenv("QML_BAD_GUI_RENDER_LOOP=0");` and `setenv("QML_BAD_GUI_RENDER_LOOP", "0", 0);` (in main.cpp) and the app does not crash...

@haampie  Can you confirm this? It would really surprise me if this magically works now. But you never know...

**Comment by haampie** [comment]
At the moment I'm on Linux only. Let me test it when I'm on my macbook again

**Comment by haampie** [comment]
It crashes for me on linux btw.

One issue I see with QueuedConnection is that the `FboRenderer` is not a QObject

**Comment by qCring** [comment]
Okay thanks, that's valuable info! I'll try to set up a Linux system in the next couple of days for testing

Yeah, you're right about the FboRenderer... I'll try to figure something out. First, I have to find a way to reproduce the crash which can take a bit. I'll keep you updated!

**Comment by haampie** [comment]
Thinking about this a bit more, I'm a bit pessimistic this can be easily solved. So the issue that jumps out is forwarding mouse events from another thread, it leads to these problems (if you're lucky you get a warning before it segfaults):

```
ERROR: In VTK-8.2.0/Common/ExecutionModel/vtkExecutive.cxx, line 802
vtkCompositeDataPipeline (0x55d4a141fe00): ProcessRequest invoked during another request.  Returning failure to algorithm vtkSphereSource(0x55d4a141f730) for the recursive request:
vtkInformation (0x55d4a141ef10)
```
but generally you cannot touch the actors, mappers, algorithms and polydata etc in general when rendering starts, right? So even if you have mutexes and queues in place to avoid mouse events from being processed during rendering, you don't really have control over the user updating properties of say a vtkSphereSource during rendering (is what I think, I don't completely have an overview how everything works in the background). Doesn't that mean that basically all operations on any vtk object have to be deferred until after rendering? And doesn't that more or less sound like a sequential application anyways?

Also it might be worth reading the qt docs:

> The non-threaded render loop is currently used by default on Windows with ANGLE or a non-default opengl32 implementation, macOS, and Linux with Mesa drivers.

Maybe this threaded render loop stuff is barely enabled anyways :p

**Comment by qCring** [comment]
Yes, I agree. I already tried the obvious steps some time ago and a clean solution for this issue seems difficult to implement. Therefore, forcing QML to run on the main thread was the best workaround at the time. 

I've also just read about the fact that most systems use the non-threaded execution of QML and I come to the same conclusion. If in your experience (since you have Linux available) the application runs well enough with `QML_BAD_GUI_RENDER_LOOP`, I'd probably just close the issue for now.

**Comment by qCring** [comment]
I'm finally closing this issue and will accept the fact that we have to live with the bad render loop...

**Comment by JensMunkHansen** [comment]
Sad to hear this is closed as a won't fix. It would be nice with a suggestion for a design where all VTK events are queued and synchronized properly in the synchronize method of the renderer.

**Comment by haampie** [comment]
Yes, maybe, but VTK explicitly states that it discourages using it with
threads (well, some of their algorithms are threaded, but that's managed by
VTK), and further you would most probably not only have to make the render
and interaction bits of VTK queued, but also updates to other parts of the
pipelines.

In Qt's threaded render loop, can you guarantee that "While the render
thread is rendering, the GUI is free to advance animations, process events,
etc." processing events do not cause mutations to actors, polydata,
algorithms and what not that the renderer accesses?

If you would have one global mutex and lock that for every call to VTK,
then sure it can be done, but it would probably be slower and bad API.

Maybe I'm oversimplifying, but I doubt it's easy to guarantee thread safety.
