### ISSUE TITLE
app (release configuration) crash on loading any qml example 

### ISSUE THREAD

**Issue by vaidotaspeckys** [qCring/QuickVtk#26]
OS: win10
Build configuration: Release. With Debug config works well.
VTK: version 7.1.0 rc1
QT: version: 5.7.0

Reproduce:
 * run app
 * click open, select any qml example from QuickVtk\res\examples\qml\simple
 * app crashes

![quickvtk _crash_on startup](https://cloud.githubusercontent.com/assets/23213872/19928838/03b954c0-a109-11e6-8fa6-7986b9ae2a63.PNG)

**Comment by qCring** [comment]
thanks for your report, Vaidotas! :)

**Comment by vaidotaspeckys** [comment]
issue not valid. Crash was caused by mixing of vtk release/debug dlls
