### ISSUE TITLE
App crashes on Ubuntu when instantiating Vtk.Viewer

### ISSUE THREAD

**Issue by qCring** [qCring/QuickVtk#31]
Seems like the vtkRenderWindowInteractor causes a crash on Linux systems

**Comment by ghost** [comment]
Using vtkGenericRenderWindowInteractor instead of vtkWin32RenderWindowInteractor on Linux seems to solve the problem (tested successfully on CentOS 7).

**Comment by qCring** [comment]
@Jbx2-0b thanks a lot for your input! I tried to blindly fix this (I don't have any linux machine around to test this) on the development branch by using an XWindow interactor on linux. If you like, create a pull-request. I would happily mention you as a contributor :)
