### ISSUE TITLE
Code Editor Formatting

### ISSUE THREAD

**Issue by qCring** [qCring/QuickVtk#32]
I still haven't figured out the best way of implementing a decent Code Editor in QML... 

The QML [TextEdit](http://doc.qt.io/qt-5/qml-qtquick-textedit.html) object provides access to a [QQuickTextDocument](http://doc.qt.io/qt-5/qquicktextdocument.html) instance, but the docs say that `You are not allowed to modify the document...`. So my guess is that the QTextCursor API can't be used for text processing. So there's still some research to do..

**Comment by haampie** [comment]
Is it really worth it writing a custom editor? Maybe a simpler option is to write a Visual Studio Code plugin instead?

**Comment by qCring** [comment]
Yes, I agree. It would be much simpler to rely on an external editor. But still, there are many advantages of a built-in solution and I'd like to try one last approach. 

Until a proper implementation, I'd like to remove the current editor and use a different strategy. I already developed a simple prototype which relies on Qt's [FileSystemWatcher](https://doc.qt.io/qt-5/qfilesystemwatcher.html). A plugin might not be necessary since most editors have some way to support QML syntax.

**Comment by haampie** [comment]
Yeah exactly, that would have been the second thing I would have proposed; just reload qml based on a file watcher. But a plugin would make it possible to highlight lines with errors in the editor during runtime.

**Comment by qCring** [comment]
I've got a first working solution and made the editor read-only for now. I'm going to close this issue since it's not really relevant anymore. 
Let me know what you think of the current implementation!

**Comment by benbatya** [comment]
What about just using the QML TextEdit so experimentation is possible? It doesn't have to have full auto complete ala QtCreator but some ability to edit would be nice.
