### ISSUE TITLE
Broken with VTK 8.2.0 on Linux

### ISSUE THREAD

**Issue by haampie** [qCring/QuickVtk#37]
I just rebuild the project with VTK 8.2.0 and Qt 5.12.3 on Ubuntu 18.04, and it seems the vtk windows is just 1 white pixel. When I resize it is sometimes shows some weird colored blocks. Do you experience the same on Linux?

**Comment by qCring** [comment]
@haampie rendering issues are finally fixed! tested on windows and macOS. Can you confirm the same for linux?

**Comment by haampie** [comment]
It works! Great! What changes were necessary to get it to work with VTK 8.2?

**Comment by qCring** [comment]
@haampie that's great news :) thanks for your quick feedback!

Check out contribution #39 for a detailed explanation!
