### ISSUE TITLE
VTK Version

### ISSUE THREAD

**Issue by kheaactua** [qCring/QuickVtk#4]
The [CMake file demands VTK v7.1.0](https://github.com/qCring/QuickVtk/blob/master/CMakeLists.txt#L78) but VTK only just recently released [7.0.0](http://www.vtk.org/download/).. Am I missing something?

Thanks

**Comment by qCring** [comment]
That's intended! When building more recent commits of VTK, the version number is already incremented to 7.1. That's the reason why QuickVtk uses 7.1 per default. If you want to use a stable release, say VTK 7.0.0, you can specify that version number directly in CMake (show advanced options and filter for "VTK")

**Comment by kheaactua** [comment]
Sounds good, thanks!
