### ISSUE TITLE
Reusing elements

### ISSUE THREAD

**Issue by haampie** [qCring/QuickVtk#41]
How would one reuse a single actor in multiple render windows?

```
Row {
  Vtk.Viewer {
    Vtk.Actor { id: actor }
  }
  Vtk.Viewer {
    // same actor
  }
}
```

Of course you could instantiate the same actor twice, but I'd like to load it only once.

Maybe something like this?

```
Vtk.Actor {
  id: actor
  ...
}

Row {
  Vtk.Viewer {
    Vtk.ActorReference {
      actor: actor
    }
  }
  Vtk.Viewer {
    Vtk.ActorReference {
      actor: actor
    }
  }
} 
```

**Comment by qCring** [comment]
Yes, just as you described it! I added an example to demonstrate this (res/examples/qml/simple/SharedActor.qml):

<code>

	import QtQuick 2.6

	import Vtk 1.0 as Vtk
	import Math 1.0 as Math

	Item {
		id: root;
		
		anchors.fill: parent;

		property real cellWidth: width/2;
		property real cellHeight: height/2;
		
		Vtk.Actor {
			id: sharedActor;

	        Vtk.PolyDataMapper {
	            Vtk.LoopSubdivisionFilter {
	                id: filter;
	                Vtk.STLReader {
	                    fileName: SampleData.meshes.suzanneSTL;
	                }
	            }
	        }
	    }

		Vtk.Viewer {
			input: sharedActor;

			width: root.cellWidth;
			height: root.cellHeight;

			mouseEnabled: true;
		}

		Vtk.Viewer {
			input: sharedActor;

			x: root.cellWidth;

			width: root.cellWidth;
			height: root.cellHeight;

			mouseEnabled: true;
		}

		Vtk.Viewer {
			input: sharedActor;

			y: root.cellHeight;
			
			width: root.cellWidth;
			height: root.cellHeight;

			mouseEnabled: true;
		}

		Vtk.Viewer {
			input: sharedActor;

			x: root.cellWidth;
			y: root.cellHeight;
			
			width: root.cellWidth;
			height: root.cellHeight;

			mouseEnabled: true;
		}
	}

 </code>

**Comment by haampie** [comment]
Perfect!
