### ISSUE TITLE
quickVtkFboOffscreenWindow.cpp:77 no member named TextureObjects

### ISSUE THREAD

**Issue by JensMunkHansen** [qCring/QuickVtk#45]
src/Core/Vtk/Internal/quickVtkFboOffscreenWindow.cpp:77:19: error: ‘class quick::Vtk::FboOffscreenWindow’ has no member named ‘TextureObjects’; did you mean ‘NoiseTextureObject’

My environment:
Debian 10
g++ 8.3.0-6. I
VTK-8.20

Are these member variables of the parents class (perhaps only using iOS?)

**Comment by qCring** [comment]
Hey @JensMunkHansen! Thanks for reporting this issue. I'll take a look into this 👍

**Comment by qCring** [comment]
Are you building VTK from `/dependencies/src/`? I just compared the `vtkOpenGLRenderWindow` implementation (8.2.0 stable on the left vs. latest on the right) and you're right, the API changed:

<img width="1673" alt="Screenshot 2019-12-18 at 17 35 41" src="https://user-images.githubusercontent.com/8017182/71108130-c1fa4d80-21c2-11ea-8075-1a931de6dd92.png">

But those changes are not stable until the next release. You're best off using the stable commit (e3de2c35c9) until experimental/nightly changes become reliable. Hope this helps!

**Comment by JensMunkHansen** [comment]
Thank you

I was using the latest. A little strange, it still carry the same version
8.2. I will go back to stable.

**Comment by qCring** [comment]
Glad I could help! Also, it's really good to know that they are changing the rendering API and be prepared for the next version, so thanks for discovering this :)
