### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by kheaactua** [qCring/QuickVtk#5]
On Linux, the cmake files because the QuickVTK target isn't defined.  I commented out the `if` condition on line 130 and it got it to work.

Also, anyone building on Linux needs to define `-DCMAKE_CXX_FLAGS="--std=c++11"`

**Comment by qCring** [comment]
awesome, thanks for your report! I've got no chance to test QuickVtk on linux atm. I'm working on mac and from time to time check out if windows still works :) If you've got some fixes for linux, feel free to create a pull request!
