### ISSUE TITLE
vtkGPUVolumeRayCastMapper: required OpenGL extension not supported

### ISSUE THREAD

**Issue by phiskus** [qCring/QuickVtk#8]
RayCaster not runable.

vtkOpenGLGPUVolumeRayCastMapper.cxx, line 4042
vtkOpenGLGPUVolumeRayCastMapper (0x10d19da00): Rendering failed because the following OpenGL extensions are required but not supported:  OpenGL 1.3 is required but not supported

**Comment by qCring** [comment]
@phiskus Thanks for the report! The latest commit on the development branch fixes this issue for Mac OS X. You'll have to rebuild VTK in the libs folder. In CMake click on File > Delete Cache for the  libs/VTK project  to rebuild VTK with OpenGL2 support and then rebuild QuickVtk. 

I'm currently working on the Windows part of the issue which can take a while. I'll update this issue as soon as OpenGL2 support also works for Windows.
